# Generated by Django 6.0.3 on 2026-05-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("idade", models.IntegerField()),
                ("fotografia", models.ImageField(upload_to="desporto/")),
            ],
        ),
        migrations.CreateModel(
            name="Desporto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "atletas",
                    models.ManyToManyField(
                        related_name="desportos", to="estudo.atleta"
                    ),
                ),
            ],
        ),
    ]
