# Generated by Django 6.0.3 on 2026-05-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desporto",
            name="atletas",
        ),
        migrations.AddField(
            model_name="atleta",
            name="desportos",
            field=models.ManyToManyField(related_name="atletas", to="estudo.desporto"),
        ),
    ]
