# Generated by Django 6.0.3 on 2026-03-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pessoa",
            new_name="Escola",
        ),
    ]
