# Generated by Django 6.0.3 on 2026-04-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="area",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="link_detalhes",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="nivel_interesse",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="orientador",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="prioridade",
        ),
        migrations.AddField(
            model_name="tfc",
            name="areas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="autores",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="pdf",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tfc",
            name="sumario",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias_usadas",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=255),
        ),
    ]
