# Generated by Django 6.0.3 on 2026-05-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_magiclinktoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MagicLinkToken",
        ),
    ]
